# -*- coding: utf-8 -*-
"""NDS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H2SPj5mD5_cVSzP5jBOXFAAzE1wKCHyj
"""

# Import necessary libraries
import cv2
import numpy as np
from google.colab.patches import cv2_imshow # Colab-specific fix for displaying images
import requests

# 1. Download the Pre-trained Haar Cascade XML file for number plates
url_xml = "https://raw.githubusercontent.com/opencv/opencv/master/data/haarcascades/haarcascade_russian_plate_number.xml"
r_xml = requests.get(url_xml)
with open('haarcascade_russian_plate_number.xml', 'wb') as f:
    f.write(r_xml.content)

# 2. Download a sample image of a car to test
url_img = "https://i.stack.imgur.com/gX33d.jpg" # Changed to a different, known-good example car image
r_img = requests.get(url_img)
with open('car_image.jpg', 'wb') as f:
    f.write(r_img.content)

print("Setup Complete! Files downloaded.")

# --- Configuration ---
image_path = 'car_image.jpg'
cascade_path = 'haarcascade_russian_plate_number.xml'

# 1. Load the Image and the Cascade
img = cv2.imread(image_path)

# Check if image was loaded successfully
if img is None:
    print(f"Error: Could not load image from {image_path}. Please check the path and file integrity.")
    # Exit or handle the error appropriately, for now we will just print and return
    # If you want to stop the cell execution, you could raise an exception or use 'return'
else:
    plate_cascade = cv2.CascadeClassifier(cascade_path)

    # 2. Convert to Grayscale
    # Haar cascades work best on grayscale images
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # 3. Detect the Plates
    # scaleFactor=1.1: Reduces image size by 10% at each scale check
    # minNeighbors=4: Higher value = fewer detections but better quality
    plates = plate_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=4)

    if len(plates) > 0:
        print(f"Found {len(plates)} number plate(s)!")

        # 4. Draw a rectangle around each detected plate
        for (x, y, w, h) in plates:
            # Arguments: image, start_point, end_point, color (Blue), thickness
            cv2.rectangle(img, (x, y), (x+w, y+h), (255, 0, 0), 3)

            # Optional: Add text label
            cv2.putText(img, "License Plate", (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (255, 0, 0), 2)

        # 5. Display the result
        cv2_imshow(img)
    else:
        print("No number plates detected. Try adjusting minNeighbors or use a clearer image.")

from google.colab import files
import cv2
import numpy as np
from google.colab.patches import cv2_imshow
import os

# --- Step 1: Check if the Haar Cascade file exists ---
cascade_filename = 'haarcascade_russian_plate_number.xml'
if not os.path.exists(cascade_filename):
    print("Error: Cascade file not found. Please run the 'Setup' code from Step 2 first.")
else:
    # --- Step 2: Create the Upload Button ---
    print("Please upload an image file (JPG or PNG)...")
    uploaded = files.upload()

    # --- Step 3: Loop through uploaded files and detect ---
    for filename in uploaded.keys():
        print(f"\nProcessing: {filename}...")

        # Load the image
        img = cv2.imread(filename)

        # Initialize the detector
        plate_cascade = cv2.CascadeClassifier(cascade_filename)

        # Convert to Grayscale
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

        # Detect plates
        plates = plate_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=4)

        if len(plates) > 0:
            # Draw rectangles
            for (x, y, w, h) in plates:
                cv2.rectangle(img, (x, y), (x+w, y+h), (0, 255, 0), 3)
                cv2.putText(img, "Plate", (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (0, 255, 0), 2)

            # Show the final image
            cv2_imshow(img)
        else:
            print("Result: No license plate detected in this image.")